[[override]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[override]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
#  version = "0.9.3"
  branch = "laullon/MONIT-15702"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/influxdata/telegraf"
  version = "1.10.3"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  branch = "master"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "0.31.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-11.0"
  name = "k8s.io/client-go"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[prune]
  go-tests = true
  unused-packages = true
