[[override]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.2"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "0.31.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.10.0"

[[constraint]]
  branch = "release-7.0"
  name = "k8s.io/client-go"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "ae27198cdd90bf12cd134ad79d1366a6cf49f632"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[prune]
  go-tests = true
  unused-packages = true
