apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-config
  namespace: 1-3-2-wavefront-collector
  annotations:
    wavefront.com/discovery-config: 'true'
data:
  collector.yaml: |
    # specify a list of discovery rules (plugins)
    plugins:
    # memcached
    - name: memcached
      type: telegraf/memcached
      selectors:
        images:
        - 'docker.io/bitnami/memcached:*'
      port: 11211
      conf: |
        servers = ["memcached-release.default.svc.cluster.local:11211"]