apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: wavefront-collector
    name: wavefront-collector
  name: wavefront-collector
  namespace: wavefront-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wavefront-collector
  template:
    metadata:
      labels:
        k8s-app: wavefront-collector
    spec:
      serviceAccountName: wavefront-collector
      containers:
      - name: wavefront-collector
        image: wavefronthq/wavefront-kubernetes-collector:1.2.5
        imagePullPolicy: IfNotPresent
        command:
        - /wavefront-collector
        - --source=kubernetes.summary_api:${MASTER_URL}?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - --sink=wavefront:?proxyAddress=wavefront-proxy.wavefront-collector.svc.cluster.local:2878&clusterName=openshift-cluster&includeLabels=true
        - --v=2
